name: Mise à jour du site Legodingo13

on:
  workflow_dispatch:

  schedule:
    - cron: "17 * * * *"

  push:
    branches:
      - main
    paths:
      - "tableau.png"
      - "update.py"
      - "fond.png"
      - "logo.png"
      - "onglet_logo.png"
      - "onglet_logo_optimise.png"
      - "favicon.ico"
      - "Youtube.png"
      - "foe_logo.png"
      - "guns.png"
      - "profil_tableau.png"
      - "roi_chute.png"
      - "forgedb.png"
      - "foe_scoredb.png"
      - "foe_data.png"
      - "banana_db.png"
      - "foe_tools.png"
      - "foe_hammer.png"
      - "foe_helper.png"
      - "ubernerd14.png"
      - "cursor_default.cur"
      - "cursor_hover.cur"
      - ".github/workflows/update-discord.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Récupérer les fichiers
        uses: actions/checkout@v7

      - name: Installer Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Générer toutes les pages du site
        run: python update.py

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v6

      - name: Préparer le site
        uses: actions/upload-pages-artifact@v5
        with:
          path: "_site"


  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: Publier le site
        id: deployment
        uses: actions/deploy-pages@v5
